name: Build and Publish .NET project to Docker Registry

on:
  push:
    branches: [ main ]  # Здесь указывается, на какие ветки будет реагировать этот workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # Клонирует ваш репозиторий

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'  # Укажите требуемую версию .NET

    - name: Build .NET project
      run: dotnet build --configuration Release

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: yourusername/yourimage:latest  # Укажите тег вашего Docker образа
